-- Seed the experiences table (2026-08-19): work / organization / education
-- history from the CV (public/CV - Muhammad Khalid Atthoriq.pdf). Mirrors the
-- remote D1 export in scripts/seed.sql. INSERT OR IGNORE so re-applying is safe.
INSERT OR IGNORE INTO "experiences" ("id","role","company","location","period","description","type","sort_order") VALUES('exp0','Front-end Developer Intern','PT Intelix Global Crossing','Malang, Indonesia','July 2026 - Present','["Optimized front-end performance using TanStack libraries.", "Modernized product UI designs with modern UX principles.", "Optimized query handling with TanStack Query for faster API queries."]','work',0);
INSERT OR IGNORE INTO "experiences" ("id","role","company","location","period","description","type","sort_order") VALUES('exp1','Fullstack Web Developer Internship','PT Surabaya Autocomp Indonesia','Ngoro, Indonesia','January 2026 - June 2026','["Developed a simulator to efficiency in production preparation.", "Optimized website performance to ensure users work smoothly in preparing mass production documents.", "Optimized workers workflow in automating documents generation."]','work',1);
INSERT OR IGNORE INTO "experiences" ("id","role","company","location","period","description","type","sort_order") VALUES('exp2','Freelance Web Developer & UI/UX Designer','Self-Employed','Malang, Indonesia','February 2024 - February 2026','["Developed and launched responsive client websites praised for clarity, speed, and strong brand alignment.", "Optimized front-end performance and accessibility, improving user satisfaction and SEO visibility.", "Delivered a food security system recognized for its reliability and ease of data handling by field users."]','work',2);
INSERT OR IGNORE INTO "experiences" ("id","role","company","location","period","description","type","sort_order") VALUES('exp3','UI/UX Designer Internship','PT Molca Teknologi Nusantara','Surabaya, Indonesia','August 2025 - October 2025','["Created Digital Twin dashboards that enhanced monitoring flow and simplified industrial decision-making.", "Collaborated closely with developers to refine design consistency, building a unified system."]','work',3);
INSERT OR IGNORE INTO "experiences" ("id","role","company","location","period","description","type","sort_order") VALUES('exp4','Creative Team Lead','Workshop Riset Informatika','Malang, Indonesia','February 2024 - February 2026','["Led the creative division to build a unified and professional brand identity across WRI''s platforms.", "Developed an adaptable content framework that encouraged consistent output and team collaboration.", "Produced and directed video campaigns well-received for storytelling and visual quality."]','organization',4);
INSERT OR IGNORE INTO "experiences" ("id","role","company","location","period","description","type","sort_order") VALUES('exp5','Informatics Engineering (BAS)','Politeknik Negeri Malang','Malang, Indonesia','August 2023 - 2027','["Focusing on Applied Informatics with a cumulative GPA of 3.7/4.0.", "Engaging in various software development projects and research workshops."]','education',5);
