#!/usr/bin/env node
// Renders scripts/og-template.html to public/og-image-<hash>.png (1200×630)
// with headless Chrome, then writes the path to src/generated/ogImage.ts.
// The card is laid out in HTML/CSS so it can reuse the site's real fonts and
// palette; Chrome rasterizes it crisply without an image lib.
//
// The filename carries a content hash: a redesigned card is a new URL, so
// social platforms and browsers pick it up instead of serving a cached copy.
// Re-run after editing scripts/og-template.html: `npm run og`.
import { execFileSync } from 'node:child_process'
import { createHash } from 'node:crypto'
import {
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  rmSync,
  writeFileSync,
} from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const template = resolve(root, 'scripts/og-template.html')
const publicDir = resolve(root, 'public')
const tmp = resolve(publicDir, '.og-image.tmp.png')
const manifest = resolve(root, 'src/generated/ogImage.ts')

const candidates = [
  process.env.CHROME_BIN,
  'google-chrome',
  'google-chrome-stable',
  'chromium',
  'chromium-browser',
  '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',
].filter(Boolean)

const chrome = candidates.find((bin) => {
  if (bin.includes('/')) return existsSync(bin)
  try {
    execFileSync('which', [bin], { stdio: 'ignore' })
    return true
  } catch {
    return false
  }
})

if (!chrome) {
  console.error('og: no Chrome/Chromium found — set CHROME_BIN to render the card')
  process.exit(1)
}

rmSync(tmp, { force: true })
execFileSync(
  chrome,
  [
    '--headless=new',
    '--disable-gpu',
    '--no-sandbox',
    '--hide-scrollbars',
    // The card references the logo SVG by file:// path.
    '--allow-file-access-from-files',
    '--force-device-scale-factor=1',
    '--window-size=1200,630',
    `--screenshot=${tmp}`,
    `file://${template}`,
  ],
  { stdio: 'inherit' },
)

const bytes = readFileSync(tmp)
const hash = createHash('sha256').update(bytes).digest('hex').slice(0, 8)
const fileName = `og-image-${hash}.png`

// Drop stale renders (previous hashes and the old unhashed og-image.png) so
// exactly one card ships and no year-cached duplicate lingers.
for (const file of readdirSync(publicDir)) {
  if (/^og-image.*\.png$/.test(file) && file !== fileName) {
    rmSync(resolve(publicDir, file), { force: true })
  }
}
writeFileSync(resolve(publicDir, fileName), bytes)
rmSync(tmp, { force: true })

mkdirSync(dirname(manifest), { recursive: true })
writeFileSync(
  manifest,
  '// AUTO-GENERATED by scripts/generate-og.mjs — run `npm run og`.\n' +
    '// Content-hashed so a redesigned card is a new URL (busts social caches).\n' +
    `export const ogImagePath = '/${fileName}'\n`,
)

console.log(`og: wrote public/${fileName}`)
