/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExperiencesIndexRouteImport } from './routes/experiences.index'
import { Route as Ls400IndexRouteImport } from './routes/ls400.index'
import { Route as MusicIndexRouteImport } from './routes/music.index'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as StatsIndexRouteImport } from './routes/stats.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperiencesIndexRoute = ExperiencesIndexRouteImport.update({
  id: '/experiences/',
  path: '/experiences/',
  getParentRoute: () => rootRouteImport,
} as any)
const Ls400IndexRoute = Ls400IndexRouteImport.update({
  id: '/ls400/',
  path: '/ls400/',
  getParentRoute: () => rootRouteImport,
} as any)
const MusicIndexRoute = MusicIndexRouteImport.update({
  id: '/music/',
  path: '/music/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsIndexRoute = StatsIndexRouteImport.update({
  id: '/stats/',
  path: '/stats/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/experiences/': typeof ExperiencesIndexRoute
  '/ls400/': typeof Ls400IndexRoute
  '/music/': typeof MusicIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/stats/': typeof StatsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/experiences': typeof ExperiencesIndexRoute
  '/ls400': typeof Ls400IndexRoute
  '/music': typeof MusicIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/stats': typeof StatsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/experiences/': typeof ExperiencesIndexRoute
  '/ls400/': typeof Ls400IndexRoute
  '/music/': typeof MusicIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/stats/': typeof StatsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/experiences/' | '/ls400/' | '/music/' | '/projects/' | '/stats/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/experiences' | '/ls400' | '/music' | '/projects' | '/stats'
  id:
    | '__root__'
    | '/'
    | '/experiences/'
    | '/ls400/'
    | '/music/'
    | '/projects/'
    | '/stats/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExperiencesIndexRoute: typeof ExperiencesIndexRoute
  Ls400IndexRoute: typeof Ls400IndexRoute
  MusicIndexRoute: typeof MusicIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  StatsIndexRoute: typeof StatsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences/': {
      id: '/experiences/'
      path: '/experiences'
      fullPath: '/experiences/'
      preLoaderRoute: typeof ExperiencesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ls400/': {
      id: '/ls400/'
      path: '/ls400'
      fullPath: '/ls400/'
      preLoaderRoute: typeof Ls400IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/music/': {
      id: '/music/'
      path: '/music'
      fullPath: '/music/'
      preLoaderRoute: typeof MusicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats/': {
      id: '/stats/'
      path: '/stats'
      fullPath: '/stats/'
      preLoaderRoute: typeof StatsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExperiencesIndexRoute: ExperiencesIndexRoute,
  Ls400IndexRoute: Ls400IndexRoute,
  MusicIndexRoute: MusicIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  StatsIndexRoute: StatsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
